results_dir: ./experiments/in1k
cloud_save_path: ./experiments/in1k
compile: True
global_seed: 42
log_every: 50
vis_every: 5000
ckpt_every: 20000
mixed_precision: bf16
no_local_save: True

dataset: azure://syn_data_wbs
image_size: 512

vq_model: AE-Diff-16
ema: True 
num_latent_tokens: 128
codebook_embed_dim: 32
perceptual_loss_weight: 0.01
latent_pos_embed_type: cross_rope

enc_type: mmdit
encoder_model: mmdit_d12 # vit_base_patch14_dinov2.lvd142m
encoder_pretrained: False
encoder_patch_size: 16
encoder_tuning_method: full
dec_type: mmdit
decoder_model: mmdit_d12
decoder_pretrained: False 
decoder_patch_size: 16
decoder_tuning_method: full
using_cfg: True
cfg_scale: 2.0

epochs: 200
lr: 1.0e-4
lr_warmup_epochs: 5
optim: adamw
lr_scheduler: cosine
weight_decay: 0.0
beta1: 0.9
beta2: 0.95
max_grad_norm: 1.0
global_batch_size: 512



